Cannot remove `ruleSet` via terraform resource `confluent_schema`
confluentinc/terraform-provider-confluent pull request #500
Opened 2024-12-03 19:27 UTC by tmalikconfluent

2025-01-03 20:03 UTC, linouk23 commented on internal/provider/resource_schema.go
> +	} else {
Will it be a good idea to use a more strict condition here by using `GetChange` similar to https://github.com/confluentinc/terraform-provider-confluent/blob/98e11aae24c179af04410ebe47854751b5a1bf36/internal/provider/resource_schema.go#L314-L316 to detect these ruleset deletions?

2025-01-03 22:22 UTC, tmalikconfluent commented on internal/provider/resource_schema.go
> +	} else {
this is just to check if  ruleset is empty and thus explicitly remove the ruleset by making it nil. I dont think we need the strong check you mentioned as it seems to be mainly for extra spaces/newlines, which shoul not be the case here as it is empty

2025-01-06 13:27 UTC, linouk23 approved these changes
Thank you for writing such a detailed testing doc!

2025-01-06 13:43 UTC, linouk23 requested changes
update: I might have identified a corner case, see https://confluent.slack.com/archives/C02TG07V058/p1736170776409049?thread_ts=1736170760.502719&cid=C02TG07V058 for more details, thank you!

2025-01-28 23:25 UTC, linouk23 commented on internal/provider/resource_schema.go
> +		Computed: false,
qq: do you remember what would be the result of running your tests if we still save `Computed: true`? Will we have TF drift or something still?

2025-01-28 23:42 UTC, tmalikconfluent commented on internal/provider/resource_schema.go
> +		Computed: false,
continuing to use computed:true leads to the deletion(setting to nil) not working at all. The empty value gets autofilled

2025-01-29 00:37 UTC, linouk23 approved these changes

2025-01-29 01:37 UTC, merged